name: Setup
description: Setup and install dependencies

inputs:
  install_flags:
    description: pnpm install flags
    default: ""

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        cache: pnpm
    - uses: pnpm/action-setup@v4
      with:
        cache: true
    - run: pnpm install --frozen-lockfile ${{ inputs.install_flags }}
      shell: bash
