name: Setup
description: Setup and install dependencies

inputs:
  install_flags:
    description: dependency install flags
    default: ""

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
    - run: bun install --frozen-lockfile ${{ inputs.install_flags }}
      shell: bash
