minimumReleaseAge: 4320 # 3 days in minutes
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
blockExoticSubdeps: true
verifyDepsBeforeRun: prompt

packages:
  - apps/*
  - packages/*

catalog:
  '@types/node24': npm:@types/node@24.13.4
  electron: 44.3.0
  oxfmt: 0.67.0
  oxlint: 1.82.0
  oxlint-tsgolint: 7.0.2001
  tsdown: 0.23.0

savePrefix: ''

allowBuilds:
  lefthook: true
  nx: true
